### ISSUE TITLE
iOS - Bugs

### ISSUE THREAD

**Issue by tianyu704** [Graan/open#3]
- [x] 日记列表内容字体颜色检查一下，感觉太浅
- [x] 编辑页markdown快捷键没出来
- [x] 有标签的笔记编辑页，点标签进入标签页，把所有标签删除，回到编辑页点击返回键直接退出了，没提示未保存弹窗
- [x] 日记编辑页点删除出提示框，点击取消，页面不要退出
- [x] 创建仓库，仓库名限制`0~9&a~z&A~Z&_`，描述可选非必填
- [x] 创建完仓库后日记列表页没刷新
- [x] 日记编辑页表情添加时顺序问题
- [x] 添加书签提示URL不合法，以下链接（https://mbd.baidu.com/newspage/data/landingpage?s_type=news&dsp=wise&context=%7B%22nid%22%3A%22news_9456276499689061930%22%7D&pageType=1&n_type=1&p_from=-1&rec_src=52）

**Comment by Li-Qun** [comment]
修改完成 特此关闭
